#!/bin/bash
SHORTHASH="$(git log -1 --pretty=%H)"
echo $SHORTHASH
echo $DOCKER_REPO:api_prod_$SHORTHASH

# docker build -t ${DOCKER_IMAGE_REPO}:web_prod_${COMMIT_ID} web --target=prod
# echo "Web built!"